#!/bin/sh
set -e

src_dir=/usr/src/php
patch_dir=/usr/src/patches

usage() {
	echo "usage: $0 [PATCH [PATCH ...]]"
	echo
	echo "Apply patches to the PHP source."
	echo
}

case "$1" in
	--help|-h|"")
		usage
		exit 1
		;;

	*)
		cd $src_dir
		for arg in "$@"; do
			patch -p0 < "$patch_dir/$arg"
		done;
		;;
esac
